### ISSUE TITLE
dependency zypper not installed

### ISSUE THREAD

**Issue by phpPhil** [kgrubb/chef-mailcatcher#10]
I found an issue in this cookbook. 
`zypper` is not declared as dependency and also not installed:

```
==> MyProject: ================================================================================
==> MyProject: Error executing action `run` on resource 'execute[Install the dependant gcc-c++]'
==> MyProject: ================================================================================
==> MyProject: Errno::ENOENT
==> MyProject: -------------
==> MyProject: No such file or directory - zypper
==> MyProject: Resource Declaration:
==> MyProject: ---------------------
==> MyProject: # In /tmp/vagrant-chef-2/chef-solo-1/cookbooks/mailcatcher/recipes/default.rb
==> MyProject:  20: execute "Install the dependant gcc-c++" do
==> MyProject:  21:  user "root"
==> MyProject:  22:  cwd "/tmp/"
==> MyProject:  23:  command "zypper -n --no-gpg-checks install -l gcc-c++" 
==> MyProject:  24:   action :run
==> MyProject:  25: end
```

As an workaround until this is fixed I add before my mailcatcher call:

```
include_recipe "zypper"
```

**Comment by kgrubb** [comment]
Ah, I don't really have suse support working full-fledged so far. I will add zypper to the suse-specific install. May I ask what version of suse you are running?

**Comment by phpPhil** [comment]
Actually, I'm not running suse, I'm running Ubuntu 14.04

**Comment by kgrubb** [comment]
Hm... weird. Ubuntu 14.04 or 14.10 shouldn't be requiring zypper. Zypper is a suse specific package manager. 

EDIT: I found the problem. You are using the mailcatcher cookbook from the supermarket. It is suse-only. My cookbook is "chef-mailcatcher". Try changing your dependency to "chef-mailcatcher" to use this cookbook.

**Comment by phpPhil** [comment]
You are right - there was a conflict between my berksfile and metadata. It was downloading the wrong cookbook :)

Sorry about this. Good on you for re-writing the other rather unmaintained mailcatcher cookbooks!

**Comment by phpPhil** [comment]
Your repo / chef supermarket cookbook is called "chef-mailcatcher", but the README reads to call it like this:

```
{
  "run_list": [
    "recipe[mailcatcher::default]"
  ]
}
```

As a suggestion to fix this I recommend to change the README file. Otherwise other people (like me) are tempted to alias it via berkshelf to "mailcatcher" which could collide with previous installations of the [mailcatcher cookbook](https://supermarket.chef.io/cookbooks/mailcatcher#dependencies)

**Comment by kgrubb** [comment]
Will do. thanks for the heads up!
